# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L-Bank.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication, QMainWindow
from classes import *
from tela_inicial import Ui_TelaLogin
from tela_cadastro import Ui_TelaCadastro
from tela_principal import Ui_TelaPrincipal

conta_atual = ''

class Ui_Main(QtWidgets.QWidget):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(640, 480)
        
        self.QtStack = QtWidgets.QStackedLayout()

        self.stack0 = QtWidgets.QMainWindow()
        self.stack1 = QtWidgets.QMainWindow()
        self.stack2 = QtWidgets.QMainWindow()

        self.tela_principal = Ui_TelaPrincipal()
        self.tela_principal.setupUi(self.stack1)

        self.tela_login = Ui_TelaLogin()
        self.tela_login.setupUi(self.stack0)
        
        self.tela_cadastro = Ui_TelaCadastro()
        self.tela_cadastro.setupUi(self.stack2)

        self.QtStack.addWidget(self.stack0)
        self.QtStack.addWidget(self.stack1)
        self.QtStack.addWidget(self.stack2)




class Main(QMainWindow, Ui_Main):
    def __init__(self):
        super(Main, self).__init__(None)
        self.setupUi(self)

        self.b = Banco()

        self.tela_login.Login_button.clicked.connect(self.abrirTelaPrincipal)
        self.tela_login.Cadastro_button.clicked.connect(self.abrirTelaCadastro)

        self.tela_cadastro.Cadastrar_button.clicked.connect(self.botao_cadastra)


        
        

    def botao_cadastra(self):
        nome = self.tela_cadastro.Nome_line.text()
        cpf = self.tela_cadastro.Cpf_line.text()
        login = self.tela_cadastro.Login_line.text()
        senha = self.tela_cadastro.Senha_line.text()

        if not(nome == '' or senha == '' or cpf == '' or login == ''):
            c = Cliente(nome,cpf)

            cc = Conta(gera_numero(self.b),c,senha,login)
            if self.b.adiciona_cliente(c,cpf) and self.b.adiciona_conta(cc,login):
                QMessageBox().information(None,'L-Bank',f'Cadastro feito com sucesso!\nSeu número é {cc.get_numero}')
                self.tela_cadastro.Nome_line.setText('')
                self.tela_cadastro.Login_line.setText('')
                self.tela_cadastro.Cpf_line.setText('')
                self.tela_cadastro.Senha_line.setText('')
            else:
                QMessageBox().information(None,'L-Bank','Titular já possui cadastrado!')
                    
        else:
            QMessageBox().information(None,'L-Bank','Todos os dados devem ser preenchidos!')

    def botao_login(self):
        login = self.tela_login.Login_line.text()
        senha = self.tela_login.Senha_line.text()

        if not(login == '' and senha == ''):
            if confirma_login(login,senha):
                conta_atual = login
                self.abrirTelaPrincipal()


    def abrirTelaCadastro(self):
        self.QtStack.setCurrentIndex(2)
    
    def abrirTelaLogin(self):
        self.QtStack.setCurrentIndex(0)
    
    def abrirTelaPrincipal(self):
        self.QtStack.setCurrentIndex(1)

    
    def finalizar(self):
        sys.exit()

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    show_main = Main()

    sys.exit(app.exec_())
