# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaCadastro(object):
    def setupUi(self, TelaCadastro):
        TelaCadastro.setObjectName("TelaCadastro")
        TelaCadastro.resize(800, 600)
        TelaCadastro.setMinimumSize(QtCore.QSize(800, 600))
        TelaCadastro.setMaximumSize(QtCore.QSize(3840, 2160))
        TelaCadastro.setSizeIncrement(QtCore.QSize(110, 100))
        TelaCadastro.setBaseSize(QtCore.QSize(800, 600))
        TelaCadastro.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(TelaCadastro)
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1200))
        self.centralwidget.setSizeIncrement(QtCore.QSize(110, 100))
        self.centralwidget.setBaseSize(QtCore.QSize(800, 600))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Fundo = QtWidgets.QLabel(self.centralwidget)
        self.Fundo.setGeometry(QtCore.QRect(0, -150, 801, 741))
        self.Fundo.setStyleSheet("background-image: url(C:/Users/LazimR/Documents/GitHub/Projeto_Banco/imagens/fundo.png);")
        self.Fundo.setText("")
        self.Fundo.setObjectName("Fundo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 30, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight Condensed")
        font.setPointSize(65)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_principal = QtWidgets.QFrame(self.centralwidget)
        self.frame_principal.setGeometry(QtCore.QRect(201, 151, 421, 271))
        self.frame_principal.setStyleSheet("background: opacity(0.0);")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.Login_label = QtWidgets.QLabel(self.frame_principal)
        self.Login_label.setGeometry(QtCore.QRect(80, 110, 50, 31))
        self.Login_label.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Login_label.setFont(font)
        self.Login_label.setObjectName("Login_label")
        self.Login_line = QtWidgets.QLineEdit(self.frame_principal)
        self.Login_line.setGeometry(QtCore.QRect(120, 110, 200, 25))
        self.Login_line.setMaximumSize(QtCore.QSize(200, 25))
        self.Login_line.setStyleSheet("border-radius:5px;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Login_line.setObjectName("Login_line")
        self.Senha_label = QtWidgets.QLabel(self.frame_principal)
        self.Senha_label.setGeometry(QtCore.QRect(70, 140, 398, 30))
        self.Senha_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Senha_label.setFont(font)
        self.Senha_label.setObjectName("Senha_label")
        self.Senha_line = QtWidgets.QLineEdit(self.frame_principal)
        self.Senha_line.setGeometry(QtCore.QRect(120, 140, 200, 25))
        self.Senha_line.setMaximumSize(QtCore.QSize(200, 25))
        self.Senha_line.setStyleSheet("border-radius:5px;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Senha_line.setObjectName("Senha_line")
        self.Cadastrar_button = QtWidgets.QPushButton(self.frame_principal)
        self.Cadastrar_button.setGeometry(QtCore.QRect(160, 190, 100, 30))
        self.Cadastrar_button.setMaximumSize(QtCore.QSize(100, 30))
        self.Cadastrar_button.setStyleSheet("border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:black;")
        self.Cadastrar_button.setObjectName("Cadastrar_button")
        self.Cpf_label = QtWidgets.QLabel(self.frame_principal)
        self.Cpf_label.setGeometry(QtCore.QRect(80, 70, 398, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Cpf_label.setFont(font)
        self.Cpf_label.setObjectName("Cpf_label")
        self.Nome_label = QtWidgets.QLabel(self.frame_principal)
        self.Nome_label.setGeometry(QtCore.QRect(70, 50, 398, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Nome_label.setFont(font)
        self.Nome_label.setStyleSheet("")
        self.Nome_label.setObjectName("Nome_label")
        self.Cpf_line = QtWidgets.QLineEdit(self.frame_principal)
        self.Cpf_line.setGeometry(QtCore.QRect(120, 80, 200, 25))
        self.Cpf_line.setMaximumSize(QtCore.QSize(200, 25))
        self.Cpf_line.setStyleSheet("border-radius:5px;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Cpf_line.setObjectName("Cpf_line")
        self.Nome_line = QtWidgets.QLineEdit(self.frame_principal)
        self.Nome_line.setGeometry(QtCore.QRect(120, 50, 200, 25))
        self.Nome_line.setMaximumSize(QtCore.QSize(200, 25))
        self.Nome_line.setStyleSheet("border-radius:5px;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Nome_line.setObjectName("Nome_line")
        self.Voltar_button = QtWidgets.QPushButton(self.frame_principal)
        self.Voltar_button.setGeometry(QtCore.QRect(160, 230, 100, 30))
        self.Voltar_button.setMaximumSize(QtCore.QSize(100, 30))
        self.Voltar_button.setStyleSheet("border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:black;")
        self.Voltar_button.setObjectName("Voltar_button")
        self.Cpf_label.raise_()
        self.Login_label.raise_()
        self.Login_line.raise_()
        self.Senha_label.raise_()
        self.Senha_line.raise_()
        self.Cadastrar_button.raise_()
        self.Nome_label.raise_()
        self.Cpf_line.raise_()
        self.Nome_line.raise_()
        self.Voltar_button.raise_()
        self.Sair_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Sair_Button.setGeometry(QtCore.QRect(700, 20, 51, 21))
        self.Sair_Button.setStyleSheet("border-radius: 2px;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color:black;\n"
"background-color:white;")
        self.Sair_Button.setObjectName("Sair_Button")
        TelaCadastro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TelaCadastro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        TelaCadastro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TelaCadastro)
        self.statusbar.setObjectName("statusbar")
        TelaCadastro.setStatusBar(self.statusbar)

        self.retranslateUi(TelaCadastro)
        QtCore.QMetaObject.connectSlotsByName(TelaCadastro)

    def retranslateUi(self, TelaCadastro):
        _translate = QtCore.QCoreApplication.translate
        TelaCadastro.setWindowTitle(_translate("TelaCadastro", "L-Bank"))
        self.label.setText(_translate("TelaCadastro", "CADASTRO"))
        self.Login_label.setText(_translate("TelaCadastro", "Login:"))
        self.Senha_label.setText(_translate("TelaCadastro", "Senha:"))
        self.Cadastrar_button.setText(_translate("TelaCadastro", "Cadastrar"))
        self.Cpf_label.setText(_translate("TelaCadastro", "CPF:"))
        self.Nome_label.setText(_translate("TelaCadastro", "Nome:"))
        self.Voltar_button.setText(_translate("TelaCadastro", "Voltar"))
        self.Sair_Button.setText(_translate("TelaCadastro", "SAIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaCadastro = QtWidgets.QMainWindow()
    ui = Ui_TelaCadastro()
    ui.setupUi(TelaCadastro)
    TelaCadastro.show()
    sys.exit(app.exec_())
